[package]
edition = "2021"
name = "cargo-features"
version = "0.1.0"

[dependencies]
anyhow = "1.0.76"
cargo = "0.77.0"
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.1.0"
semver = "1.0.20"
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"

