[package]
edition = "2021"
name = "cargo-features"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
cargo = "0.67.0"
clap = { version = "4.0.30", features = ["derive"] }
colored = "2.0.0"
semver = "1.0.16"
toml = "0.5.10"
